### ISSUE TITLE
Fails when running stashapp inside Docker

### ISSUE THREAD

**Issue by kdbruin** [rustyinfinity/StashNfoExporter#1]
I'm running stashapp inside a Docker container (hotio.dev) and get the following error:

```
ModuleNotFoundError: No module named 'lxml'
```

How can I add `lxml` to my Docker container? I'm using `docker compose` to manage my stack.

**Comment by rustyinfinity** [comment]
> I'm running stashapp inside a Docker container (hotio.dev) and get the following error:
> 
> ```
> ModuleNotFoundError: No module named 'lxml'
> ```
> 
> How can I add `lxml` to my Docker container? I'm using `docker compose` to manage my stack.

You have to install lxml module you can do it by 

```docker-compose exec Stash(or whatever container id) (bash or sh or whatever shell) ```
```pip install lxml```
or
```docker exec -it CONTAINER_ID (bash or sh or whatever shell)```
```pip install lxml```

and i have added requirments.txt so u can go to plugin path from 
```docker-compose exec Stash(or whatever container id) (bash or sh or whatever shell )```
 and install like this 
```pip install -r requirments.txt --break-system-packages```

I have shown in how i do.


<img width="1180" alt="Screenshot 2024-01-21 at 7 21 49 PM" src="https://github.com/rustyinfinity/StashNfoExporter/assets/115462641/a7151ecc-116f-4a27-93cf-7eca98e9e4a0">

If this error shows add --break-system-packages


# How i do
<img width="623" alt="Screenshot 2024-01-21 at 7 24 39 PM" src="https://github.com/rustyinfinity/StashNfoExporter/assets/115462641/4946242e-a2c2-4a99-8287-6cb47172cffe">

<img width="1209" alt="Screenshot 2024-01-21 at 7 27 11 PM" src="https://github.com/rustyinfinity/StashNfoExporter/assets/115462641/84996f35-5c3e-4b25-8ce0-4b2d21a87ae0">

<img width="1552" alt="Screenshot 2024-01-21 at 7 29 11 PM" src="https://github.com/rustyinfinity/StashNfoExporter/assets/115462641/528232ac-5704-47b8-a107-8cad8f942c39">
