### ISSUE TITLE
`.nfo` isn't generated for new files

### ISSUE THREAD

**Issue by Tetrax-10** [rustyinfinity/StashNfoExporter#3]
### To trigger the process I edited the latest `76 - Cum In My Greenhouse` scene

![image](https://github.com/rustyinfinity/StashNfoExporter/assets/75513645/e41c9a44-9920-4924-a169-c35c4f2ae04f)
![image](https://github.com/rustyinfinity/StashNfoExporter/assets/75513645/82643783-e90f-44eb-b002-c4c40e41b462)

**Comment by rustyinfinity** [comment]
> ### To trigger the process I edited the latest `76 - Cum In My Greenhouse` scene
> 
> ![image](https://private-user-images.githubusercontent.com/75513645/305651099-e41c9a44-9920-4924-a169-c35c4f2ae04f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMTY2MjIsIm5iZiI6MTcwODIxNjMyMiwicGF0aCI6Ii83NTUxMzY0NS8zMDU2NTEwOTktZTQxYzlhNDQtOTkyMC00OTI0LWExNjktYzM1YzRmMmFlMDRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDAwMzIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyODNkNzA3MWY4Mzk2MTNjNDFiNGQ5OTg3Y2RjMTlhMDEwMmQwMzY3MDM0ZjJmZmQ3MzI4ZmZkOTgxZTBjNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PX5KU7PLXjaz0GdDKgruGNz8olka7pPPGPv_ienphRI) ![image](https://private-user-images.githubusercontent.com/75513645/305651108-82643783-e90f-44eb-b002-c4c40e41b462.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMTY2MjIsIm5iZiI6MTcwODIxNjMyMiwicGF0aCI6Ii83NTUxMzY0NS8zMDU2NTExMDgtODI2NDM3ODMtZTkwZi00NGViLWIwMDItYzRjNDBlNDFiNDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDAwMzIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MjZlMjUxYzdjZTI4Nzg3MWFmOWQ3MzkzZDZkYTFmYzY0NjkxNzM3NThjZTBkYzFkNzkzNjcyZjJiNTM4MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.usD-TxA4Jax2pjVZeUeM4AFQiGFDLfEKsrEVaIeIkKk)

Are You using latest version ?

**Comment by rustyinfinity** [comment]
Try using latest version @Tetrax-10 if there is still problem tell me :)

**Comment by Tetrax-10** [comment]
### Still the same
![image](https://github.com/rustyinfinity/StashNfoExporter/assets/75513645/97b1f34c-43a8-4bb3-bde6-f9e3cb9567a9)
![image](https://github.com/rustyinfinity/StashNfoExporter/assets/75513645/eb52b399-33ad-42ff-b800-2bdf92784b03)

**Comment by Tetrax-10** [comment]
Ahh crap its my mistake. I didn't set organized for those new videos. sry.

Also try using the new plugin manager. Because people usually forget about the plugins after they install and they always have the outdated one till the plugin get broke. Using plugin manager people can auto update plugins.

**Comment by rustyinfinity** [comment]
> Ahh crap its my mistake. I didn't set organized for those new videos. sry.
> 
> Also try using the new plugin manager. Because people usually forget about the plugins after they install and they always have the outdated one till the plugin get broke. Using plugin manager people can auto update plugins.

Sure I will try it once i get some time . Thanks for helping as always  :)
