### ISSUE TITLE
Error erxecuting post hooks

### ISSUE THREAD

**Issue by MRobi1** [rustyinfinity/StashNfoExporter#4]
```
2024-02-19 15:17:15
Error   
error executing post hooks: operation cancelled
```

When I enable this plugin and set a file to organized, it will sit and hang. Sometimes after about 10 minutes it will complete and I'll get an NFO generated. The majority of times I just get this error in the log. When I disable the plugin again, organizing is speedy and everything completes.

When it does complete, I get a different error. But NFO is generated and appears correct.
```
4-02-19 15:23:13
Error   
Scene.Update.Post [Stash NFO Exporter]: returned error: exit status 1
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter] ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter]   File "src/lxml/apihelpers.pxi", line 1541, in lxml.etree._utf8
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter]   File "src/lxml/apihelpers.pxi", line 736, in lxml.etree._createTextNode
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter]   File "src/lxml/apihelpers.pxi", line 748, in lxml.etree._setNodeText
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter]     ^^^^^^^^^^^^^^^^^
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter]   File "src/lxml/etree.pyx", line 1042, in lxml.etree._Element.text.__set__
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter]     plot_element.text = details
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter]   File "/root/.stash/plugins/StashNfoExporter-main/StashNfoExporter.py", line 244, in generateNFO
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter]     result = self.fn(*self.args, **self.kwargs)
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter]     raise self._exception
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter]   File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter]            ^^^^^^^^^^^^^^^^^^^
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter]   File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter]     return self.__get_result()
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter]              ^^^^^^^^^^^^^^^
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter]   File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter]     result = future.result()
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter]   File "/root/.stash/plugins/StashNfoExporter-main/StashNfoExporter.py", line 391, in main
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter]     main()
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter] Traceback (most recent call last):
2024-02-19 15:23:13
Error   
[Plugin / Stash NFO Exporter]   File "/root/.stash/plugins/StashNfoExporter-main/StashNfoExporter.py", line 401, in <module>
```

**Comment by rustyinfinity** [comment]
> ```
> 2024-02-19 15:17:15
> Error   
> error executing post hooks: operation cancelled
> ```
> 
> When I enable this plugin and set a file to organized, it will sit and hang. Sometimes after about 10 minutes it will complete and I'll get an NFO generated. The majority of times I just get this error in the log. When I disable the plugin again, organizing is speedy and everything completes.
> 
> When it does complete, I get a different error. But NFO is generated and appears correct.
> 
> ```
> 4-02-19 15:23:13
> Error   
> Scene.Update.Post [Stash NFO Exporter]: returned error: exit status 1
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter] ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter]   File "src/lxml/apihelpers.pxi", line 1541, in lxml.etree._utf8
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter]   File "src/lxml/apihelpers.pxi", line 736, in lxml.etree._createTextNode
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter]   File "src/lxml/apihelpers.pxi", line 748, in lxml.etree._setNodeText
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter]     ^^^^^^^^^^^^^^^^^
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter]   File "src/lxml/etree.pyx", line 1042, in lxml.etree._Element.text.__set__
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter]     plot_element.text = details
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter]   File "/root/.stash/plugins/StashNfoExporter-main/StashNfoExporter.py", line 244, in generateNFO
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter]     result = self.fn(*self.args, **self.kwargs)
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter]     raise self._exception
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter]   File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter]            ^^^^^^^^^^^^^^^^^^^
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter]   File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter]     return self.__get_result()
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter]              ^^^^^^^^^^^^^^^
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter]   File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter]     result = future.result()
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter]   File "/root/.stash/plugins/StashNfoExporter-main/StashNfoExporter.py", line 391, in main
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter]     main()
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter] Traceback (most recent call last):
> 2024-02-19 15:23:13
> Error   
> [Plugin / Stash NFO Exporter]   File "/root/.stash/plugins/StashNfoExporter-main/StashNfoExporter.py", line 401, in <module>
> ```

For That performance Issue I have improved performance by 9x so it would not take 10mins until its a very huge database and about this error that you faced I think it is caused by reading function that i implemented earlier where string was being decoded . I have removed it as it was causing it to slow. You can try latest plugin code  if it still pop ups then tell me .

**Comment by MRobi1** [comment]
Speed has certainly improved, but I still wouldn't call it fast. My organize flow consists of renameOnUpdate and stashNFOExporter. With the NFO exporter disabled, to organize a file took 8s. Enabling it, it took 59s. It's a considerable improvement 

Shorter error message this time. But now no NFO is being generated.

```
2024-02-24 21:03:21
Error   
Scene.Update.Post [Stash NFO Exporter]: returned error: exit status 1
2024-02-24 21:03:21
Error   
[Plugin / Stash NFO Exporter] ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
2024-02-24 21:03:21
Error   
[Plugin / Stash NFO Exporter]   File "src/lxml/apihelpers.pxi", line 1541, in lxml.etree._utf8
2024-02-24 21:03:21
Error   
[Plugin / Stash NFO Exporter]   File "src/lxml/apihelpers.pxi", line 736, in lxml.etree._createTextNode
2024-02-24 21:03:21
Error   
[Plugin / Stash NFO Exporter]   File "src/lxml/apihelpers.pxi", line 748, in lxml.etree._setNodeText
2024-02-24 21:03:21
Error   
[Plugin / Stash NFO Exporter]   File "src/lxml/etree.pyx", line 1042, in lxml.etree._Element.text.__set__
2024-02-24 21:03:21
Error   
[Plugin / Stash NFO Exporter]     ^^^^^^^^^^^^^^^^^
2024-02-24 21:03:21
Error   
[Plugin / Stash NFO Exporter]     plot_element.text = scene['details']
2024-02-24 21:03:21
Error   
[Plugin / Stash NFO Exporter]   File "/root/.stash/plugins/StashNfoExporter-main/StashNfoExporter.py", line 87, in process_scene
2024-02-24 21:03:21
Error   
[Plugin / Stash NFO Exporter]            ^^^^^^^^^^^^^^^^^^^^
2024-02-24 21:03:21
Error   
[Plugin / Stash NFO Exporter]     root = process_scene(scene)
2024-02-24 21:03:21
Error   
[Plugin / Stash NFO Exporter]   File "/root/.stash/plugins/StashNfoExporter-main/StashNfoExporter.py", line 228, in <module>
2024-02-24 21:03:21
Error   
[Plugin / Stash NFO Exporter] Traceback (most recent call last):
```

**Comment by rustyinfinity** [comment]
> Speed has certainly improved, but I still wouldn't call it fast. My organize flow consists of renameOnUpdate and stashNFOExporter. With the NFO exporter disabled, to organize a file took 8s. Enabling it, it took 59s. It's a considerable improvement
> 
> Shorter error message this time. But now no NFO is being generated.
> 
> ```
> 2024-02-24 21:03:21
> Error   
> Scene.Update.Post [Stash NFO Exporter]: returned error: exit status 1
> 2024-02-24 21:03:21
> Error   
> [Plugin / Stash NFO Exporter] ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
> 2024-02-24 21:03:21
> Error   
> [Plugin / Stash NFO Exporter]   File "src/lxml/apihelpers.pxi", line 1541, in lxml.etree._utf8
> 2024-02-24 21:03:21
> Error   
> [Plugin / Stash NFO Exporter]   File "src/lxml/apihelpers.pxi", line 736, in lxml.etree._createTextNode
> 2024-02-24 21:03:21
> Error   
> [Plugin / Stash NFO Exporter]   File "src/lxml/apihelpers.pxi", line 748, in lxml.etree._setNodeText
> 2024-02-24 21:03:21
> Error   
> [Plugin / Stash NFO Exporter]   File "src/lxml/etree.pyx", line 1042, in lxml.etree._Element.text.__set__
> 2024-02-24 21:03:21
> Error   
> [Plugin / Stash NFO Exporter]     ^^^^^^^^^^^^^^^^^
> 2024-02-24 21:03:21
> Error   
> [Plugin / Stash NFO Exporter]     plot_element.text = scene['details']
> 2024-02-24 21:03:21
> Error   
> [Plugin / Stash NFO Exporter]   File "/root/.stash/plugins/StashNfoExporter-main/StashNfoExporter.py", line 87, in process_scene
> 2024-02-24 21:03:21
> Error   
> [Plugin / Stash NFO Exporter]            ^^^^^^^^^^^^^^^^^^^^
> 2024-02-24 21:03:21
> Error   
> [Plugin / Stash NFO Exporter]     root = process_scene(scene)
> 2024-02-24 21:03:21
> Error   
> [Plugin / Stash NFO Exporter]   File "/root/.stash/plugins/StashNfoExporter-main/StashNfoExporter.py", line 228, in <module>
> 2024-02-24 21:03:21
> Error   
> [Plugin / Stash NFO Exporter] Traceback (most recent call last):
> ```

I have added checks to only update files which have changed first scan will take some. time though and the. error that. you. were getting should. not come. also as that. was caused by your details of scene had some invalid characters i have fixed that.

**Comment by MRobi1** [comment]
Seems to be working. 
It appears on the first run it started generating NFO's on other files in the database and after a few minutes came back as operation cancelled. After that first file, it now generates only on the file being organized and not seeing any further errors.

So I guess my next question is, is there a way to run this manually as a task to go through the entire database and generate files for any that may be missing? Possibly a feature enhancement.

Edit to add my entire organized flow is now taking around 10s which is another significant improvement over the last update. Well done!

**Comment by rustyinfinity** [comment]
> Seems to be working. It appears on the first run it started generating NFO's on other files in the database and after a few minutes came back as operation cancelled. After that first file, it now generates only on the file being organized and not seeing any further errors.
> 
> So I guess my next question is, is there a way to run this manually as a task to go through the entire database and generate files for any that may be missing? Possibly a feature enhancement.
> 
> Edit to add my entire organized flow is now taking around 10s which is another significant improvement over the last update. Well done!

Added It !
I also run rename and mover and it was getting annoying as nfo was getting made in downloading directory so i added it to task page so now you can go and run it manually after it get renamed and moved to the directory.
 It will not run autmatically for now.
