### ISSUE TITLE
Can't create Nfo

### ISSUE THREAD

**Issue by arlynners** [rustyinfinity/StashNfoExporter#6]
Scene.Update.Post [Stash NFO Exporter]: returned error: exit status 1
2024-02-26 23:39:50
Error   
[Plugin / Stash NFO Exporter] TypeError: 'NoneType' object is not subscriptable
2024-02-26 23:39:50
Error   
[Plugin / Stash NFO Exporter]                           ~~~~~~^^^^^^^^
2024-02-26 23:39:50
Error   
[Plugin / Stash NFO Exporter]     studio_element.text = studio['name']
2024-02-26 23:39:50
Error   
[Plugin / Stash NFO Exporter]   File "/plugin/StashNfoExporter/StashNfoExporter.py", line 96, in process_scene
2024-02-26 23:39:50
Error   
[Plugin / Stash NFO Exporter]            ^^^^^^^^^^^^^^^^^^^^
2024-02-26 23:39:50
Error   
[Plugin / Stash NFO Exporter]     root = process_scene(scene)
2024-02-26 23:39:50
Error   
[Plugin / Stash NFO Exporter]   File "/plugin/StashNfoExporter/StashNfoExporter.py", line 228, in <module>
2024-02-26 23:39:50
Error   
[Plugin / Stash NFO Exporter] Traceback (most recent call last):

**Comment by rustyinfinity** [comment]
> Scene.Update.Post [Stash NFO Exporter]: returned error: exit status 1 2024-02-26 23:39:50 Error [Plugin / Stash NFO Exporter] TypeError: 'NoneType' object is not subscriptable 2024-02-26 23:39:50 Error [Plugin / Stash NFO Exporter] ~~~~~~^^^^^^^^ 2024-02-26 23:39:50 Error [Plugin / Stash NFO Exporter] studio_element.text = studio['name'] 2024-02-26 23:39:50 Error [Plugin / Stash NFO Exporter] File "/plugin/StashNfoExporter/StashNfoExporter.py", line 96, in process_scene 2024-02-26 23:39:50 Error [Plugin / Stash NFO Exporter] ^^^^^^^^^^^^^^^^^^^^ 2024-02-26 23:39:50 Error [Plugin / Stash NFO Exporter] root = process_scene(scene) 2024-02-26 23:39:50 Error [Plugin / Stash NFO Exporter] File "/plugin/StashNfoExporter/StashNfoExporter.py", line 228, in 2024-02-26 23:39:50 Error [Plugin / Stash NFO Exporter] Traceback (most recent call last):

Fixed

**Comment by arlynners** [comment]
Some of the NFO files the cast is in actor and then it works but sometime its in set and then it doesnt work. Same for when the genres are not working because they are only in tags. It also sometime wont load the pictures in jellyfin
