### ISSUE TITLE
Jellyfin doesn't import tumbnails 

### ISSUE THREAD

**Issue by arlynners** [rustyinfinity/StashNfoExporter#7]
When I try too refresh movie with replace all i can this error 

[2024-03-02 02:06:06.701 +00:00] [ERR] [25] MediaBrowser.Providers.Movies.MovieMetadataService: Could not save "Logo" image: "http://192.168.2.117:9999/studio/43/image?t=1709297143&default=true"
System.Net.Http.HttpRequestException: Invalid image received.
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, CancellationToken cancellationToken)
[2024-03-02 02:06:06.704 +00:00] [ERR] [18] MediaBrowser.Providers.Movies.MovieMetadataService: Could not save "Thumb" image: "http://192.168.2.117:9999/scene/763/screenshot?t=1709336686"
System.Net.Http.HttpRequestException: Invalid image received.
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, CancellationToken cancellationToken)
[2024-03-02 02:06:06.708 +00:00] [ERR] [18] MediaBrowser.Providers.Movies.MovieMetadataService: Could not save "Primary" image: "http://192.168.2.117:9999/scene/763/screenshot?t=1709336686"
System.Net.Http.HttpRequestException: Invalid image received.
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, CancellationToken cancellationToken)
[2024-03-02 02:06:06.710 +00:00] [ERR] [18] MediaBrowser.Providers.Movies.MovieMetadataService: Could not save "Backdrop" image: "http://192.168.2.117:9999/scene/763/screenshot?t=1709336686"
System.Net.Http.HttpRequestException: Invalid image received.
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, CancellationToken cancellationToken)

**Comment by rustyinfinity** [comment]
> When I try too refresh movie with replace all i can this error
> 
> [2024-03-02 02:06:06.701 +00:00] [ERR] [25] MediaBrowser.Providers.Movies.MovieMetadataService: Could not save "Logo" image: "http://192.168.2.117:9999/studio/43/image?t=1709297143&default=true" System.Net.Http.HttpRequestException: Invalid image received. at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken) at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, CancellationToken cancellationToken) [2024-03-02 02:06:06.704 +00:00] [ERR] [18] MediaBrowser.Providers.Movies.MovieMetadataService: Could not save "Thumb" image: "http://192.168.2.117:9999/scene/763/screenshot?t=1709336686" System.Net.Http.HttpRequestException: Invalid image received. at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken) at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, CancellationToken cancellationToken) [2024-03-02 02:06:06.708 +00:00] [ERR] [18] MediaBrowser.Providers.Movies.MovieMetadataService: Could not save "Primary" image: "http://192.168.2.117:9999/scene/763/screenshot?t=1709336686" System.Net.Http.HttpRequestException: Invalid image received. at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken) at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, CancellationToken cancellationToken) [2024-03-02 02:06:06.710 +00:00] [ERR] [18] MediaBrowser.Providers.Movies.MovieMetadataService: Could not save "Backdrop" image: "http://192.168.2.117:9999/scene/763/screenshot?t=1709336686" System.Net.Http.HttpRequestException: Invalid image received. at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken) at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, CancellationToken cancellationToken)

I think It is causing because you have api key.
I have found the fix i have to add "?apikey=xxx" after the url of images in the nfo files for the people using api key.
It is fairly easy but will take me 2-3 days because I have a exam. 
For the time being you can remove the api key and scan  with jellyfin and it will store it in the cache.
Thanks

**Comment by arlynners** [comment]
> > When I try too refresh movie with replace all i can this error
> > [2024-03-02 02:06:06.701 +00:00] [ERR] [25] MediaBrowser.Providers.Movies.MovieMetadataService: Could not save "Logo" image: "http://192.168.2.117:9999/studio/43/image?t=1709297143&default=true" System.Net.Http.HttpRequestException: Invalid image received. at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken) at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, CancellationToken cancellationToken) [2024-03-02 02:06:06.704 +00:00] [ERR] [18] MediaBrowser.Providers.Movies.MovieMetadataService: Could not save "Thumb" image: "http://192.168.2.117:9999/scene/763/screenshot?t=1709336686" System.Net.Http.HttpRequestException: Invalid image received. at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken) at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, CancellationToken cancellationToken) [2024-03-02 02:06:06.708 +00:00] [ERR] [18] MediaBrowser.Providers.Movies.MovieMetadataService: Could not save "Primary" image: "http://192.168.2.117:9999/scene/763/screenshot?t=1709336686" System.Net.Http.HttpRequestException: Invalid image received. at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken) at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, CancellationToken cancellationToken) [2024-03-02 02:06:06.710 +00:00] [ERR] [18] MediaBrowser.Providers.Movies.MovieMetadataService: Could not save "Backdrop" image: "http://192.168.2.117:9999/scene/763/screenshot?t=1709336686" System.Net.Http.HttpRequestException: Invalid image received. at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken) at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, CancellationToken cancellationToken)
> 
> I think It is causing because you have api key. I have found the fix i have to add "?apikey=xxx" after the url of images in the nfo files for the people using api key. It is fairly easy but will take me 2-3 days because I have a exam. For the time being you can remove the api key and scan with jellyfin and it will store it in the cache. Thanks

Which API key that from stash ?

**Comment by rustyinfinity** [comment]
> > > When I try too refresh movie with replace all i can this error
> > > [2024-03-02 02:06:06.701 +00:00] [ERR] [25] MediaBrowser.Providers.Movies.MovieMetadataService: Could not save "Logo" image: "http://192.168.2.117:9999/studio/43/image?t=1709297143&default=true" System.Net.Http.HttpRequestException: Invalid image received. at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken) at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, CancellationToken cancellationToken) [2024-03-02 02:06:06.704 +00:00] [ERR] [18] MediaBrowser.Providers.Movies.MovieMetadataService: Could not save "Thumb" image: "http://192.168.2.117:9999/scene/763/screenshot?t=1709336686" System.Net.Http.HttpRequestException: Invalid image received. at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken) at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, CancellationToken cancellationToken) [2024-03-02 02:06:06.708 +00:00] [ERR] [18] MediaBrowser.Providers.Movies.MovieMetadataService: Could not save "Primary" image: "http://192.168.2.117:9999/scene/763/screenshot?t=1709336686" System.Net.Http.HttpRequestException: Invalid image received. at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken) at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, CancellationToken cancellationToken) [2024-03-02 02:06:06.710 +00:00] [ERR] [18] MediaBrowser.Providers.Movies.MovieMetadataService: Could not save "Backdrop" image: "http://192.168.2.117:9999/scene/763/screenshot?t=1709336686" System.Net.Http.HttpRequestException: Invalid image received. at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken) at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, CancellationToken cancellationToken)
> > 
> > 
> > I think It is causing because you have api key. I have found the fix i have to add "?apikey=xxx" after the url of images in the nfo files for the people using api key. It is fairly easy but will take me 2-3 days because I have a exam. For the time being you can remove the api key and scan with jellyfin and it will store it in the cache. Thanks
> 
> Which API key that from stash ?

yes

**Comment by rustyinfinity** [comment]
do you have credentials set up in stash ?

**Comment by arlynners** [comment]
yes and have turned if off and now it works

**Comment by arlynners** [comment]
It doesn't show the actors anymore i need to bring the actors higher in the NFOexporter file for it to work

**Comment by rustyinfinity** [comment]
> It doesn't show the actors anymore i need to bring the actors higher in the NFOexporter file for it to work

I fixed it you can try it out !
